package managegarage;
import javax.swing.JFrame;
/**
 *
 * @author Khang Nguyen
 */
public class HomeFr extends javax.swing.JFrame {

    /**
     * Creates new form HomeFr
     */
    public HomeFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Employee = new javax.swing.JLabel();
        NameEmp = new javax.swing.JLabel();
        Customer = new javax.swing.JLabel();
        Bill = new javax.swing.JLabel();
        Services = new javax.swing.JLabel();
        NameCus = new javax.swing.JLabel();
        NameSer = new javax.swing.JLabel();
        Namebill = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Garage");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 600));
        jPanel2.setLayout(null);

        Employee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/businessman.png"))); // NOI18N
        Employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Employee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeMouseClicked(evt);
            }
        });
        jPanel2.add(Employee);
        Employee.setBounds(100, 150, 130, 140);

        NameEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameEmp.setText("Employee");
        jPanel2.add(NameEmp);
        NameEmp.setBounds(95, 285, 140, 22);

        Customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/people.png"))); // NOI18N
        Customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Customer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
        });
        jPanel2.add(Customer);
        Customer.setBounds(500, 150, 130, 140);

        Bill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        Bill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillMouseClicked(evt);
            }
        });
        jPanel2.add(Bill);
        Bill.setBounds(100, 380, 130, 140);

        Services.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/car.png"))); // NOI18N
        Services.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Services.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServicesMouseClicked(evt);
            }
        });
        jPanel2.add(Services);
        Services.setBounds(500, 390, 130, 140);

        NameCus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameCus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameCus.setText("Customer");
        jPanel2.add(NameCus);
        NameCus.setBounds(510, 285, 120, 22);

        NameSer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameSer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameSer.setText("Services");
        jPanel2.add(NameSer);
        NameSer.setBounds(520, 510, 100, 22);

        Namebill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Namebill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Namebill.setText("Bill");
        jPanel2.add(Namebill);
        Namebill.setBounds(120, 510, 87, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Manage garage.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1, 3, 750, 130);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        // TODO add your handling code here:
        CustomerFr a = new CustomerFr();
        a.setVisible(true);
    }//GEN-LAST:event_CustomerMouseClicked

    private void EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseClicked
        // TODO add your handling code here:
        EmployeeFr a = new EmployeeFr();
        a.setVisible(true);
    }//GEN-LAST:event_EmployeeMouseClicked

    private void BillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillMouseClicked
        BillFr a = new BillFr();
        a.setVisible(true);
    }//GEN-LAST:event_BillMouseClicked

    private void ServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMouseClicked
        ServicesFr a = new ServicesFr();
        a.setVisible(true);
    }//GEN-LAST:event_ServicesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bill;
    private javax.swing.JLabel Customer;
    private javax.swing.JLabel Employee;
    private javax.swing.JLabel NameCus;
    private javax.swing.JLabel NameEmp;
    private javax.swing.JLabel NameSer;
    private javax.swing.JLabel Namebill;
    private javax.swing.JLabel Services;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
